name: all_about_music
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  go_router: ^14.1.3
  firebase_core: ^2.31.1
  cloud_firestore: ^4.17.4
  firebase_auth: ^4.19.6
  firebase_storage: ^11.7.6
  flutter_svg: ^2.0.10+1
  csc_picker: ^0.2.7
  image_picker: ^1.1.2
  file_picker: ^8.0.3
  uuid: ^4.4.0
  audioplayers: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/splash.png
    - assets/images/onboarding1.png
    - assets/images/onboarding2.png
    - assets/images/onboarding3.png
    - assets/images/music_cover.png
    - assets/images/rapper.png
    - assets/icons/gear.svg
    - assets/icons/menu.svg

  fonts:
    - family: Cypher1
      fonts:
        - asset: assets/fonts/Cypher1.ttf
    - family: Cypher2
      fonts:
        - asset: assets/fonts/Cypher2.ttf
    - family: HelveticaNeue
      fonts:
        - asset: assets/fonts/HelveticaNeue-Regular.ttf
        - asset: assets/fonts/HelveticaNeue-Light.otf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
        - asset: assets/fonts/Montserrat-Light.ttf
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
        - asset: assets/fonts/Lato-Black.ttf
